image:
- Visual Studio 2019
- Ubuntu
- macOS
stack: node 10
environment:
  nodejs_version: "10"
  GITHUB_TOKEN:
    secure: t1s7bP+lo6z4Gv+F0J2pvD4KY2nzgdtOtrz/eN3Q41XgoV4+GnBtuY2oHQdQJ1nH
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- '$HOME/.cache/electron'
- '$HOME/.npm'
- node_modules
branches:
  only:
  - forge6
  - master
  - /^v\d\.\d\.\d/
install:
- ps: |
    if ($isWindows) {
      Install-Product node $env:nodejs_version $env:platform
      Set-Item -Path Env:Path -Value ($Env:AppData + "\npm;" + $Env:Path)
    }
- cmd: echo %PATH%
- cmd: dir %APPDATA%\npm
- sh: |
    env
    if test "$(uname -s)" = "Linux"; then
      sudo apt-get install --yes --no-install-recommends snapcraft
      ci/install_snap_dependencies.sh
    fi
- npm install
- npm update

test_script:
- node --version
- npm --version
- npm run lint
- cmd: if %APPVEYOR_REPO_TAG% EQU false npm run make
- sh: if test -z "$APPVEYOR_REPO_TAG"; then npm run make; fi

build_script:
- cmd: IF %APPVEYOR_REPO_TAG% EQU true npm run publish
- sh: if test -n "$APPVEYOR_REPO_TAG"; then npm run publish; fi
