image: Visual Studio 2017
platform:
- x64
environment:
  nodejs_version: "6"
  ELECTRON_FORGE_ELECTRON_WINSTALLER_CONFIG_CERTIFICATE_PASSWORD: CertPassword
  GITHUB_TOKEN:
    secure: t1s7bP+lo6z4Gv+F0J2pvD4KY2nzgdtOtrz/eN3Q41XgoV4+GnBtuY2oHQdQJ1nH
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- node_modules
branches:
  only:
  - master
  - forge-657
  - /^v\d\.\d\.\d/
install:
- ps: |
    $cert = New-SelfSignedCertificate -DnsName developer@example.com -Type CodeSigningCert -CertStoreLocation cert:\CurrentUser\My
    $path = 'cert:\CurrentUser\My\' + $cert.thumbprint
    $certPassword = ConvertTo-SecureString -String "CertPassword" -Force –AsPlainText
    Export-PfxCertificate -cert $path -FilePath selfsigncert.pfx -Password $certPassword
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update

test_script:
- node --version
- npm --version
- npm run lint
- if %APPVEYOR_REPO_TAG% EQU false npm run make -- --platform=win32 --targets=squirrel

build_script:
- IF %APPVEYOR_REPO_TAG% EQU true npm run publish
