image:
- Visual Studio 2019
- Ubuntu
- macOS
stack: node 10
environment:
  nodejs_version: "10"
  GITHUB_TOKEN:
    secure: t1s7bP+lo6z4Gv+F0J2pvD4KY2nzgdtOtrz/eN3Q41XgoV4+GnBtuY2oHQdQJ1nH
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- '$HOME/.cache/electron'
- '$HOME/.npm'
- node_modules
branches:
  only:
  - forge6
  - master
  - /^v\d\.\d\.\d/
install:
# - ps: Install-Product node $env:nodejs_version $env:platform
- cmd: set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update

test_script:
- node --version
- npm --version
- npm run lint
- cmd: if %APPVEYOR_REPO_TAG% EQU false npm run make

build_script:
- cmd: IF %APPVEYOR_REPO_TAG% EQU true npm run publish
