image:
- Visual Studio 2019
- Ubuntu
- macOS
stack: node 10
environment:
  nodejs_version: "10"
  GITHUB_TOKEN:
    secure: t1s7bP+lo6z4Gv+F0J2pvD4KY2nzgdtOtrz/eN3Q41XgoV4+GnBtuY2oHQdQJ1nH
cache:
- '%APPDATA%\npm-cache'
- '%LOCALAPPDATA%\electron\Cache'
- '$HOME/.cache/electron'
- '$HOME/Library/Caches/electron'
- '$HOME/.npm'
- node_modules
branches:
  only:
  - forge6
  - master
  - /^v\d\.\d\.\d/
install:
- ps: |
    if ($isWindows) {
      Install-Product node $env:nodejs_version
    }
- sh: ci/install_snap_dependencies.sh
- npm install
- npm update

test_script:
- node --version
- npm --version
- npm run lint
- cmd: if %APPVEYOR_REPO_TAG% EQU false npm run make
- sh: if test "$APPVEYOR_REPO_TAG" = "false"; then npm run make; fi

build_script:
- cmd: IF %APPVEYOR_REPO_TAG% EQU true npm run publish
- sh: if test "$APPVEYOR_REPO_TAG" = "true"; then npm run publish; fi
