language: node_js
node_js: "10"
os:
- linux
- osx
- windows
dist: bionic
osx_image: xcode10.1

cache:
  npm: true
  yarn: true
  directories:
  - $HOME/.cache/electron
  - $HOME/Library/Caches/electron
  - $HOME/AppData/Local/electron/Cache

addons:
  apt:
    packages:
    - fakeroot
    - rpm

env:
  - DEBUG: electron-installer-snap:snapcraft
    YARN_GPG: no

before_install: ci/install_snap_dependencies.sh

script:
- yarn lint
- if test -z "$TRAVIS_TAG"; then yarn make; fi
after_success: if test -n "$TRAVIS_TAG"; then yarn publish; fi
