language: node_js
node_js: "10"
os:
- linux
- osx
dist: bionic
osx_image: xcode10.1

cache:
  npm: true
  yarn: true
  directories:
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

env:
  - DEBUG: electron-installer-snap:snapcraft

before_install:
- sudo apt-get install --yes --no-install-recommends snapcraft
- ci/install_snap_dependencies.sh

install:
- npm install
- npm update

script:
- npm run lint
- if test -z "$TRAVIS_TAG"; then npm run make; fi
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi
