name: Build

on:
  push:
    branches:
      - forge6
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Snapcraft setup
        run: |
          sudo apt-get install --yes --no-install-recommends snapcraft
          ci/install_snap_dependencies.sh
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-build-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install
        run: |
          npm install --engine-strict
          npm update
      - name: Build
        run: npm run make
        env:
          DEBUG: electron-installer-snap:snapcraft
